-- SOLUTION:

SELECT DISTINCT CITY
FROM STATION
WHERE (CITY NOT RLIKE '^[AEIOU]') OR (CITY NOT RLIKE '[AEIOU]$');

-- OR

-- SELECT DISTINCT CITY
-- FROM STATION
-- WHERE (CITY NOT REGEXP '^[AEIOU]') OR (CITY NOT REGEXP '[AEIOU]$');