-- SOLUTION

SELECT DISTINCT CITY
FROM STATION
WHERE ((CITY RLIKE '[AEIUO]$') AND (CITY RLIKE '^[AEIUO]'));

-- OR

-- SELECT DISTINCT CITY
-- FROM STATION
-- WHERE ((CITY REGEXP '[AEIUO]$') AND (CITY REGEXP '^[AEIUO]'));